server:
  port: 8083

spring:
  application:
    name: task_service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/clarity_tasks
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true