server:
  port: 8081

spring:
  application:
    name: user-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/clarity_users
      auto-index-creation: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ClaritySecretKeyForJWTTokenGenerationMustBeLongEnough123456
  expiration: 3600000