server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_service
          uri: lb://user_service
          predicates:
            - Path=/api/users/**
        
        - id: habit_service
          uri: lb://habit_service
          predicates:
            - Path=/api/habits/**
        
        - id: reflection_service
          uri: lb://reflection_service
          predicates:
            - Path=/api/reflections/**
        
        - id: analytics_service
          uri: lb://analytics_service
          predicates:
            - Path=/api/analytics/**
        
        - id: quote_service
          uri: lb://quote_service
          predicates:
            - Path=/api/quotes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true